### ISSUE TITLE
[FEATURE] Add new formulas templates types

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-templates#1]
Related to this issue: https://github.com/ZupIT/ritchie-cli/issues/1016

**What would you like to be added**:

- Update the repository structure to be able to support different formulas templates.

**Why is this needed**:

- Today, the templates repository only support `hello-world` templates, the idea would be to add new templates such as `Empty`, `REST API consuming`, `Project Scaffolding` and so on... in as many programming language as possible.

**Comment by fabianofernandeszup** [comment]
The PR resolved this issue 
https://github.com/ZupIT/ritchie-templates/pull/8
